### PR TITLE
More precise setting paths on the "Roblox not opening" page

### PR DESCRIPTION
**Pull request by kamild1996**
### Type
- [x] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [x] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request
A single change to make setting paths more precise on the "Roblox not opening" page.

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
You can set commit titles, you know.

**Comment by kamild1996** [comment]
> You can set commit titles, you know.

My bad, I really don't use GitHub on a regular basis :)

**Comment by Xyueta** [comment]
Looks good, thanks.

**Comment by Ast3risk-ops** [comment]
Could have used icons for the windows versions 😞

**Pull request merged**
