### PR TITLE
New installation guide

### PR DESCRIPTION
**Pull request by he3als**
### Type
- [x] Rewrite already written documentation.
- [x] Add/remove new pages.

### Questions
- [x] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request
Adds a new installation guide utilising the Windows Setup. This means that no USB will be required to install Atlas, and you won't have to dual boot to do so.

**Preview:** https://new-install.atlasos-docs-enq.pages.dev/getting-started/installation/

### CODE REVIEW

**Review by JayXTQ — DISMISSED** [review]
Doesn't look too bad

**Review by JayXTQ — APPROVED** [review]
Don't request reviews if you are going to change my guy

**Comment by he3als** [comment]
I don't have anymore changes now, but I thought I didn't before soo...

**Comment by PencilNavigator** [comment]
doesn't look 2 bad

**Review by PencilNavigator — APPROVED** [review]

**Comment by PONGSATHONSAMAEUN** [comment]
704b437

**Pull request merged**
