### PR TITLE
Add a new Windows reinstall method using Ventoy 

### PR DESCRIPTION
**Pull request by kul-sudo**
### Type
- [x] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [x] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request
On Discord I think there's been everything from people typing in `oobe\byypassnro` to people ignoring this step altogether, so it's probably a good idea to let people avoid that completely.
Another good reason is that it's pretty intuitive: you get the ISO, drag it into the Ventoy USB stick, and it just works. Right now it's assumed the user already has Windows installed somewhere, so this change will allow to in the future explain Linux users how to install Atlas on their machines (that'll probably be my next PR), because Ventoy is supported on Linux.

There's also a tiny change removing a period, because it isn't used in the other tips. Sorry for the double commit, by the way.

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
Sir you forgot to add your venv to the gitignore

**Comment by kul-sudo** [comment]
> Sir you forgot to add your venv to the gitignore

I did, that's why I had to remove it and commit again. I just don't really do Python, so I missed that.

**Comment by Ast3risk-ops** [comment]
well I can't see what you edited as github dies when trying to render your venv, so I'll have to pull this

**Comment by kul-sudo** [comment]
> well I can't see what you edited as github dies when trying to render your venv, so I'll have to pull this.
> 
> Also Rufus can do far more patches than Ventoy ever coukd

I agree, but that's too many things to explain to a normal user, so Ventoy would be preferred as an alternative installation method.

**Comment by Ast3risk-ops** [comment]
> > well I can't see what you edited as github dies when trying to render your venv, so I'll have to pull this.
> > Also Rufus can do far more patches than Ventoy ever coukd
> 
> I agree, but that's too many things to explain to a normal user, so Ventoy would be preferred as an alternative installation method.

I disagree, Rufus is quite simple and intuitive, and it works every time unlike Ventoy.

**Comment by kul-sudo** [comment]
> > > well I can't see what you edited as github dies when trying to render your venv, so I'll have to pull this.
> > > Also Rufus can do far more patches than Ventoy ever coukd
> > 
> > I agree, but that's too many things to explain to a normal user, so Ventoy would be preferred as an alternative installation method.
> 
> I disagree, Rufus is quite simple and intuitive, and it works every time unlike Ventoy.

Well, if you secure boot is off and you follow the manual I've composed, it should always work.

**Comment by Ast3risk-ops** [comment]
Just pulled this, what have you done.

**Comment by kul-sudo** [comment]
> Just pulled this, what have you done.

See the diff.

**Comment by Ast3risk-ops** [comment]
> > Just pulled this, what have you done.
> 
> See the diff.

github lags when rendering it because you pushed a venv, cloned your fork and am viewing it locally

**Comment by Ast3risk-ops** [comment]
I would honestly close this, USB install is an afterthought for us anyway, we don't need a method like this (that is also not as well explained and makes the existing tip admonition too long)

**Comment by kul-sudo** [comment]
> > > Just pulled this, what have you done.
> > 
> > See the diff.
> 
> github lags when rendering it because you pushed a venv, cloned your fork and am viewing it locally

Oh, my bad again. I'll delete the env real quick. Hold on.

**Comment by Ast3risk-ops** [comment]
> > > > Just pulled this, what have you done.
> > > 
> > > 
> > > See the diff.
> > 
> > 
> > github lags when rendering it because you pushed a venv, cloned your fork and am viewing it locally
> 
> Oh, my bad again. I'll delete the env real quick. Hold on.

no dont, you can't do anything about that

**Comment by Ast3risk-ops** [comment]
> Just pulled this, what have you done. We do not go into detail on USB install for a reason, 99% of people do not need to do it.

and you made the info admonition *too long*, now people have to scroll past it.

**Comment by kul-sudo** [comment]
> > Just pulled this, what have you done. We do not go into detail on USB install for a reason, 99% of people do not need to do it.
> 
> and you made the info admonition _too long_, now people have to scroll past it. Also you put a note admonition on the video when there are written instructions already (i'd just put that in the guide itself)

No, it's actually already removed in the latest commit https://github.com/Atlas-OS/docs/pull/190/commits/c878e9318ca13d9442745df901a60bc56867e12f :thinking:

**Comment by kul-sudo** [comment]
> Just curious if you've worked with material for mkdocs before.

No, and I've barely worked with Python expect for my most popular project.

**Comment by Ast3risk-ops** [comment]
> > Just curious if you've worked with material for mkdocs before.
> 
> No, and I've barely worked with Python expect for my most successful project.

I mean material for mkdocs in general, you don't need to know Python for that.

**Comment by kul-sudo** [comment]
> > > Just curious if you've worked with material for mkdocs before.
> > 
> > No, and I've barely worked with Python expect for my most successful project.
> 
> I mean material for mkdocs in general, you don't need to know Python for that. It's quite powerful

No, I haven't.

**Comment by Ast3risk-ops** [comment]
Another thing, your ventoy dl link is *wrong*

**Comment by kul-sudo** [comment]
> Another thing, your ventoy dl link is *wrong*, it'll pin to a specific version. Use `https://github.com/ventoy/Ventoy/releases/latest`

The thing is that they also store the version in the name of the zip. Moreover, in case they change the UI radically, I don't want the docs to immediately become misleading.

**Comment by Ast3risk-ops** [comment]
> > Another thing, your ventoy dl link is _wrong_, it'll pin to a specific version. Use `https://github.com/ventoy/Ventoy/releases/latest`
> 
> The thing is that they also store the version in the name of the zip. Moreover, in case they change the UI radically, I don't want the docs to immediately become misleading, so a specific version is safer.

Just tell people what to click. Ventoy's UI will not change, and it's better for them to get updates (also you only link a windows download)

**Comment by kul-sudo** [comment]
> > > Another thing, your ventoy dl link is _wrong_, it'll pin to a specific version. Use `https://github.com/ventoy/Ventoy/releases/latest`
> > 
> > The thing is that they also store the version in the name of the zip. Moreover, in case they change the UI radically, I don't want the docs to immediately become misleading, so a specific version is safer.
> 
> Just tell people what to click on the download page. Ventoy's UI will not change, and it's better for them to get updates (also you only link a windows download)

All right.

**Comment by kul-sudo** [comment]
> > Just pulled this, what have you done. We do not go into detail on USB install for a reason, 99% of people do not need to do it.
> 
> and you made the info admonition _too long_, now people have to scroll past it. Also you put a note admonition on the video when there are written instructions already (i'd just put that in the guide itself)

You mean the video?

**Comment by kul-sudo** [comment]
@Ast3risk-ops Hey, sorry for so many useless commit, I just couldn't figure something out for some time. Enough about commits, is it better now?

**Comment by Ast3risk-ops** [comment]
> @Ast3risk-ops Hey, sorry for so many commits, I just couldn't figure something out for some time. Enough about commits, is it better now?

Reecommended for simplified setup is not true, we do not recommend Ventoy.

**Comment by kul-sudo** [comment]
> > @Ast3risk-ops Hey, sorry for so many commits, I just couldn't figure something out for some time. Enough about commits, is it better now?
> 
> Reecommended for simplified setup is not true, we do not recommend Ventoy.
> 
> Rufus can also do "simplified setup" but we don't endorse that either.

Removing then. Better now? Also, pay attention to the video I've edited.

**Comment by Ast3risk-ops** [comment]
> > > @Ast3risk-ops Hey, sorry for so many commits, I just couldn't figure something out for some time. Enough about commits, is it better now?
> > 
> > 
> > Reecommended for simplified setup is not true, we do not recommend Ventoy.
> > Rufus can also do "simplified setup" but we don't endorse that either.
> 
> Removing then. Better now? Also, pay attention to the video I've edited.

The edit is kinda bad ngl, but honestly just don't shoehorn that in everywhere, just say in the ventoy instructions to skip that.

**Comment by kul-sudo** [comment]
> > > > @Ast3risk-ops Hey, sorry for so many commits, I just couldn't figure something out for some time. Enough about commits, is it better now?
> > > 
> > > 
> > > Reecommended for simplified setup is not true, we do not recommend Ventoy.
> > > Rufus can also do "simplified setup" but we don't endorse that either.
> > 
> > 
> > Removing then. Better now? Also, pay attention to the video I've edited.
> 
> The edit is kinda bad ngl, but honestly just don't shoehorn that in everywhere, just say in the ventoy instructions (and only there) to skip that, to avoid user confusion.

Fair enough, I've ditched it :+1:

**Comment by he3als** [comment]
Hi - I'm going to merge this and potentially do some minor changes to formatting and such. If you have any suggestions for my changes, feel free to open an issue or another PR.

This is a very good contribution, so thank you!

**Comment by Ast3risk-ops** [comment]
ChatGPT and our MSDL thing helped me make this weird thing to fetch the latest release properly:

```html
<script>
    function replace() {
        var styleSheet = document.createElement("style")
        styleSheet.innerText = '.ventoy { display: revert !important }'
        document.head.appendChild(styleSheet)
    }
</script>

<style>
    .ventoy {
        display: none;
    }
</style>

[Download Button](javascript:replace();){ .md-button }


<div id="latest-release-info" class="ventoy"></div>

<script>
   const apiUrl = 'https://api.github.com/repos/ventoy/ventoy/releases/latest';
   fetch(apiUrl)
     .then(response => {
       if (!response.ok) {
         throw new Error('Network response was not ok');
       }
       return response.json();
     })
     .then(data => {
       const latestReleaseInfo = document.getElementById('latest-release-info');
       latestReleaseInfo.innerHTML = `
         <p><a href="${data.assets[3].browser_download_url}" target="_blank" class="md-button" rel="noopener noreferrer">Windows Download</a> <a href="${data.assets[1].browser_download_url}" target="_blank" class="md-button" rel="noopener noreferrer">Linux Download</a></p>
       `;
     })
     .catch(error => {
       console.error('Error fetching data:', error);
     });
</script>

```

**Pull request merged**
