### PR TITLE
feat: switch to mkdocs-macros

### PR DESCRIPTION
**Pull request by Ast3risk-ops**
### Type
- [ ] Rewrite already written documentation
- [ ] Add/remove new pages

### Questions
- [x] Did you preview your changes beforehand?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?

### Describe your pull request

Switch to `mkdocs-macros` instead of using a file for variables. Unfortunately macros and variables don't render on pages that the user doesn't see (or maybe just pages loaded via `pymdownx.snippets`), so MSDL has been moved back to `installation.md`. I don't know a way around this yet.

### CODE REVIEW

**Review by he3als — APPROVED** [review]

**Review by he3als — DISMISSED** [review]

**Comment by Ast3risk-ops** [comment]
Where did the atlas version go?

**Comment by Ast3risk-ops** [comment]
Did you test that? It'll be missing the %20s.

**Comment by he3als** [comment]
Yes

**Comment by Ast3risk-ops** [comment]
> Yes

Yeah it works. lgtm.

**Pull request merged**
