### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by PencilNavigator**
### Type
- [ ] Rewrite already written documentation.
- [ ] Add/remove new pages.
- [x] Add License
### Questions
- [ ] Did you preview on your local machine beforehand?
- [ ] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?

### Describe your pull request
Adding license.
Any discussions are welcome at https://github.com/Atlas-OS/docs/issues/73

merging this resolves https://github.com/Atlas-OS/docs/issues/73

### CODE REVIEW

**Review by JayXTQ — DISMISSED** [review]
honestly, idc, but lgtm

**Review by Xyueta — CHANGES_REQUESTED** [review]
No need for two licenses.

**Comment by JayXTQ** [comment]
CC doesn't work with code apparently @Xyueta

**Comment by PencilNavigator** [comment]
https://github.com/Atlas-OS/docs/issues/73#issuecomment-1537177897
changed to only one license (CC-BY-SA 4.0)

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
