### PR TITLE
fix: kaspersky realtime free no longer exists

### PR DESCRIPTION
**Pull request by Ast3risk-ops**
### Type
- [x] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [ ] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request

Kaspersky realtime free no longer exists, removed it from AV listing.

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
Don't merge yet, adding defender too.

**Comment by Ast3risk-ops** [comment]
done.

**Comment by jacksyrm** [comment]
Not available to commit to the fork, please alter:

Offers lightweight, fast, constantly updating and simple protection. Comes with Windows.

to

Lightweight, consistently updated malware definitions and native protection inside of Windows.

**Comment by Ast3risk-ops** [comment]
> Not available to commit to the fork, please alter:
> 
> Offers lightweight, fast, constantly updating and simple protection. Comes with Windows.
> 
> to
> 
> Lightweight, consistently updated malware definitions and native protection inside of Windows.

The request changes button exists Jack :)

**Pull request merged**
