### PR TITLE
Add Photos to post install docs 

### PR DESCRIPTION
**Pull request by coffandro**
### Type
- [x] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [ ] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request
I think adding photos to the post install docs would be justified

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
I find photos too slow, but to each their own.

**Comment by coffandro** [comment]
Yeah, it probably also steal just about all your data but I still think the option should be in the docs personally

**Comment by coffandro** [comment]
also the description is in no way final, just modified the Films and TV text

**Comment by kul-sudo** [comment]
> Yeah, it probably also steal just about all your data but I still think the option should be in the docs personally

I doubt it'll steal data :thinking:

**Comment by Xyueta** [comment]
We will make a separate category for Photo Viewer soon, thanks though.

**Pull request closed without merging**
