### PR TITLE
fix: ⚡️url issues with %20

### PR DESCRIPTION
**Pull request by JayXTQ**
- replace %20 with - and uncapatalised urls.
- changed all urls to use this new format

### CODE REVIEW

**Comment by JayXTQ** [comment]
Wait, draft this rq. Issues with navigation!

**Comment by JayXTQ** [comment]
should be fixed now

**Review by PencilNavigator — DISMISSED** [review]
lgtm
i did the same thing and didn't managed to get it working, probably because i forgot to change the config.yml file

**Comment by PencilNavigator** [comment]
@JayXTQ accesing “https://3d21784f.atlasos-docs-enq.pages.dev/Troubleshooting/scripts.md” returns 404 not found

**Comment by JayXTQ** [comment]
because you did /Troubleshooting/ not /troubleshooting/

**Pull request merged**
