### PR TITLE
refactor: refactor the 'no-usb' documentation MD file

### PR DESCRIPTION
**Pull request by CrownedMatrix**
### Type
- [x] Rewrite already written documentation.
- [ ] Add/remove new pages.

### Questions
- [x] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request
re-wrote no-usb.md to be more user friendly and not dual-boot.

### CODE REVIEW

**Comment by CrownedMatrix** [comment]
This is a more simply way to install AtlasOS without a USB Drive. ( Also doesn't involve risk to your computer )

**Comment by CrownedMatrix** [comment]
> This is a more simply way to install AtlasOS without a USB Drive. ( Also doesn't involve risk to your computer )

If this is accepted, my discord is Chronos#0002

**Comment by sabaasa** [comment]
this should be merged, remove the streamable.com video though

**Comment by CrownedMatrix** [comment]
> this should be merged, remove the streamable.com video though

The streamable is from the original USB Installation post.

**Comment by sabaasa** [comment]
alr
nice pull request

**Comment by PencilNavigator** [comment]
FYI, this method was discussed before internally and confirmed to work. Was planning to write something simliar recently.

**Comment by CrownedMatrix** [comment]
> FYI, this method was discussed before internally and confirmed to work. Was planning to write something simliar recently.

Oh alright! I'm glad that a new No USB method was in consideration. I'm glad to help in any way!

I've tested this method with 7 people so far and it seems to work 100% of the time.

It's also a lot more friendly for Computer Illiterate people.

**Review by PencilNavigator — APPROVED** [review]
lgtm

**Review by Xyueta — APPROVED** [review]

**Pull request merged**
