### PR TITLE
fix(social): work on social cards

### PR DESCRIPTION
**Pull request by whallin**
### Questions
- [x] Did you preview on your local machine beforehand?
- [x] Did you follow our [commit handbook](https://github.com/Atlas-OS/docs/blob/master/.github/CONTRIBUTING.md#commit-message)?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [x] Did you commit to the `dev` branch and not `master`?

### Describe your pull request

* Restructure of configs
   * Now use ``mkdocs.yml`` for all configuration, while ``mkdocs.insiders.yml`` only contains configurations for **Insider plugins**.
* Fix for social cards

### CODE REVIEW

**Comment by whallin** [comment]
Seems to build as intended now?

**Comment by JayXTQ** [comment]
Any image to prove that they embed?

**Comment by whallin** [comment]
> Any image to prove that they embed?

See hyperlink above your comment.

https://f9011e08.atlasos-docs-enq.pages.dev/assets/images/social/index.png

**Comment by JayXTQ** [comment]
oh mb didnt see that

**Review by JayXTQ — APPROVED** [review]
Doesn't look too bad

**Review by SyrmGIT — APPROVED** [review]

**Pull request merged**
