### PR TITLE
feat(troubleshooting): playbook stuck page

### PR DESCRIPTION
**Pull request by he3als**
### Type
- [ ] Rewrite already written documentation
- [x] Add/remove new pages

### Questions
- [x] Did you preview your changes beforehand?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?

### Describe your pull request

Adds a page for 'Action is taking too long' and 'Reticulating Splines,' with potential fixes and explaining what it means.

### CODE REVIEW

**Comment by nicklvh** [comment]
LGTM

**Comment by Ast3risk-ops** [comment]
You could also add that you can check the last modified date of the log files.

**Review by RadNotRed — APPROVED** [review]
lgtm

**Review by the-P1neapple — APPROVED** [review]

**Comment by he3als** [comment]
> You could also add that you can check the last modified time of the log files.

Show Logs takes you to the latest log directory

**Pull request merged**
