### PR TITLE
feat: update troubleshooting, move to atlas config

### PR DESCRIPTION
**Pull request by he3als**
### Type
- [x] Rewrite already written documentation
- [ ] Add/remove new pages

### Questions
- [x] Did you preview your changes beforehand?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?

### Describe your pull request
Moves the troubleshooting page under Atlas Configuration, where the rest of the folders are. Also updates it for v0.5.0.

https://new-troubleshooting.atlasos-docs-enq.pages.dev/getting-started/post-installation/atlas-folder/troubleshooting/

### CODE REVIEW

**Review by the-P1neapple — CHANGES_REQUESTED** [review]
To make it less confusing for users. Can you add a page in the troubleshooting area to redirect troubleshooting scripts the new location?

**Comment by he3als** [comment]
> To make it less confusing for users. Can you add a page in the troubleshooting area to redirect troubleshooting scripts the new location?

There's a link redirect, but I don't think an actual redirect in the sidebar is necessary. It would make sense to look for the 'Troubleshooting' folder under the Atlas folders section.

**Review by the-P1neapple — APPROVED** [review]
Understandable, all good then.

**Review by RadNotRed — APPROVED** [review]
lgtm

**Pull request merged**
