### PR TITLE
Removed a space that broke command

### PR DESCRIPTION
**Pull request by scanash00**
The command is: manage-bde -autounlock -ClearAllKeys %SystemDrive%

The command that was told in the website was  manage-bde -autounlock -ClearAllKeys %SystemDrive% which gave an output of: "-" was not understood.

### Type
- [x] Rewrite already written documentation
- [ ] Add/remove new pages

### Questions
- [x] Did you preview your changes beforehand?
- [x] Did you read the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?

### CODE REVIEW

**Comment by scanash00** [comment]
image

**Comment by Ast3risk-ops** [comment]
lgtm

**Review by RadNotRed — APPROVED** [review]
lgtm, good job whoever made this page

**Review by the-P1neapple — APPROVED** [review]
Good find. Thanks Scan

**Pull request merged**
